nezukosite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

from photouploader import urls as photouploader_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(photouploader_urls, namespace='photouploader'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photouploader/urls.py
from django.urls import path
from .views import HomePageView, PhotoPostDetailView, PostPhotoView

app_name = 'photouploader'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PhotoPostDetailView.as_view(), name='detail'),
    path('post/', PostPhotoView.as_view(), name='post'),
]

photouploader/models.py
from django.db import models
from django.db.models.fields import TextField
from sorl.thumbnail import ImageField

# Create your models here.
class PostPhoto(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    caption = TextField()
    image = ImageField()

    def __str__(self) -> str:
        return self.title

photouploader/forms.py
from django import forms

class PostPhotoForm(forms.Form):
    title = forms.CharField(max_length=100)
    caption = forms.CharField(widget=forms.Textarea)
    image = forms.ImageField()

photouploader/views.py
from django.db.models.base import Model
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, FormView

from .models import PostPhoto
from .forms import PostPhotoForm

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photo_post'] = PostPhoto.objects.all()
        return context

class PhotoPostDetailView(DetailView):
    template_name = 'detail.html'
    model = PostPhoto
    
class PostPhotoView(FormView):
    template_name = 'post.html'
    form_class = PostPhotoForm
    success_url = '/'

    def form_valid(self, form):

        new_object = PostPhoto.objects.create(
            title = form.cleaned_data['title'],
            caption = form.cleaned_data['caption'],
            image = form.cleaned_data['image']
        )

        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Nezuko Site{% endblock title %}</title>
</head>
<body>
    {% block body %}{% endblock body %}
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %} Detail {% endblock title %}

{% block body %}
    <a href={% url 'photouploader:index' %}><-- go back</a>
    <img src={{ object.image.url }} style='width: 100%;'>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Home Page{% endblock title %}

{% block body %}
    {% for post in photo_post %}
        <a href={% url 'photouploader:detail' post.id %}>
        <h4>{{ post.title }}</h4>
        {% thumbnail post.image "150x150" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        </a>
        <p> {{ post.caption }} </p>
        <hr>
    {% endfor %}
{% endblock body %}

templates/post.html
{% extends 'base.html' %}

{% block title %} Post Photo {% endblock title %}

{% block body %}
    <form method='post' action='' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type='submit' name='submit' value='Submit Form'>
    </form>
{% endblock body %}